### PR TITLE
Fixed namespace of CacheClientInterface

### PR DESCRIPTION
**Pull request by bartoszjuszczyk**

### CODE REVIEW

**Comment by enanobots** [comment]
@bartoszjuszczyk  thanks, this will be update din 24,0h

**Comment by bartoszjuszczyk** [comment]
@enanobots some progress?

**Comment by jakwinkler** [comment]
To be fair, I've forgotten about this one :-) Merge in a moment ;-)

**Comment by jakwinkler** [comment]
New tag `1.0.3` created , thanks for reminding me, you can always catch on Discord (jakubwinkler) or on `MageChat`

**Pull request merged**
